"""YouTube authentication and error classification.

Handles configured cookies safely without exposing them in logs, frontend state,
or public coordinator events.
"""

from __future__ import annotations

import asyncio
import io
import os
from typing import Any, Optional

import yt_dlp.cookies

from services.youtube.errors import (
	PlaylistNotSupportedError,
	SourceAccessDeniedError,
	SourceAuthRequiredError,
	SourceNotFoundError,
	YouTubeError,
)


def get_youtube_cookies_path() -> Optional[str]:
	"""Return path to YouTube cookie file if configured via file path, otherwise None."""
	configured_path = os.environ.get("YOUTUBE_COOKIES_FILE")
	if configured_path and os.path.isfile(configured_path):
		return configured_path
	return None


def get_youtube_ydl_auth_opts() -> dict[str, Any]:
	"""Return yt-dlp authentication options without exposing raw contents."""
	cookie_path = get_youtube_cookies_path()
	if cookie_path:
		return {"cookiefile": cookie_path}
	return {}


def create_cookiejar_from_netscape(cookie_content: str) -> Optional[yt_dlp.cookies.YoutubeDLCookieJar]:
	"""Parse Netscape cookie file content in-memory without touching the filesystem."""
	if not cookie_content or not cookie_content.strip():
		return None
	try:
		if not cookie_content.startswith("# Netscape"):
			cookie_content = "# Netscape HTTP Cookie File\n" + cookie_content
		jar = yt_dlp.cookies.YoutubeDLCookieJar()
		jar._really_load(io.StringIO(cookie_content), "in_memory", ignore_discard=True, ignore_expires=True)
		if not list(jar):
			return None
		return jar
	except Exception:
		return None


def export_cookiejar_to_netscape(jar: yt_dlp.cookies.YoutubeDLCookieJar) -> str:
	"""Export in-memory cookiejar to standard Netscape cookie file format."""
	lines = [
		"# Netscape HTTP Cookie File",
		"# This file was generated by AppView. Do not edit.\n",
	]
	for cookie in jar:
		domain = cookie.domain
		initial_dot = "TRUE" if domain.startswith(".") else "FALSE"
		path = cookie.path or "/"
		secure = "TRUE" if cookie.secure else "FALSE"
		expires = str(cookie.expires) if cookie.expires is not None and cookie.expires > 0 else "2147483647"
		name = cookie.name
		value = cookie.value or ""
		if name and value:
			lines.append(f"{domain}\t{initial_dot}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
	return "\n".join(lines) + "\n"


def has_essential_session_cookies(jar: yt_dlp.cookies.YoutubeDLCookieJar) -> bool:
	"""Check whether the cookiejar contains essential logged-in session tokens."""
	session_keys = {"SID", "__Secure-1PSID", "__Secure-3PSID", "SSID", "HSID"}
	for cookie in jar:
		if cookie.name in session_keys and cookie.value and cookie.value.strip():
			return True
	return False


def detect_cookie_changes(
	original_raw: Optional[str],
	jar: yt_dlp.cookies.YoutubeDLCookieJar,
) -> tuple[bool, Optional[str]]:
	"""Compare jar with original raw cookies.

	Returns (True, new_netscape_content) if any cookie value was changed or new cookies added,
	while strictly ensuring that essential session cookies are preserved.
	"""
	if not has_essential_session_cookies(jar):
		return False, None

	new_netscape = export_cookiejar_to_netscape(jar)
	if not original_raw or not original_raw.strip():
		return True, new_netscape

	orig_jar = create_cookiejar_from_netscape(original_raw)
	if not orig_jar:
		return True, new_netscape

	orig_map = {
		(c.domain.lower().lstrip("."), c.path or "/", c.name): c.value
		for c in orig_jar
	}

	has_changes = False
	for c in jar:
		key = (c.domain.lower().lstrip("."), c.path or "/", c.name)
		orig_val = orig_map.get(key)
		if orig_val is None or orig_val != c.value:
			has_changes = True
			break

	if has_changes:
		return True, new_netscape

	return False, None


async def verify_youtube_cookies(raw_cookies: str) -> tuple[bool, str]:
	"""Test candidate cookies against YouTube in-memory without filesystem access."""
	if not raw_cookies or not raw_cookies.strip():
		return False, "Nội dung cookies trống."

	jar = create_cookiejar_from_netscape(raw_cookies)
	if jar is None:
		return False, "Định dạng cookies không hợp lệ. Vui lòng cung cấp định dạng Netscape cookie file."

	yt_cookies = [c for c in jar if "youtube.com" in c.domain or "google.com" in c.domain]
	if not yt_cookies:
		return False, "Không tìm thấy cookies cho youtube.com hoặc google.com."

	loop = asyncio.get_running_loop()
	try:
		return await loop.run_in_executor(None, _test_youtube_cookies_sync, jar)
	except Exception as err:
		return False, f"Xác thực thất bại: {err}"


def _test_youtube_cookies_sync(jar: yt_dlp.cookies.YoutubeDLCookieJar) -> tuple[bool, str]:
	import re
	import yt_dlp

	ydl_opts: dict[str, Any] = {
		"quiet": True,
		"no_warnings": True,
		"skip_download": True,
		"socket_timeout": 15,
		"http_headers": {
			"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
			"Accept-Language": "vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7",
		},
	}
	try:
		ydl = yt_dlp.YoutubeDL(ydl_opts)
		ydl.cookiejar = jar
		resp = ydl.urlopen("https://www.youtube.com/")
		html = resp.read().decode("utf-8", errors="ignore")

		logged_in_match = re.search(r'"LOGGED_IN"\s*:\s*(true|false)', html, re.IGNORECASE)
		if logged_in_match:
			is_logged_in = logged_in_match.group(1).lower() == "true"
			if not is_logged_in:
				return False, "Cookies YouTube chưa đăng nhập hoặc đã hết hạn (LOGGED_IN: false). Cần đầy đủ session cookies (SID, HSID, SSID, __Secure-1PSID, __Secure-1PSIDTS...) từ trình duyệt."

		return True, "Xác thực cookies YouTube thành công."
	except Exception as err:
		error_msg = str(err).lower()
		if any(w in error_msg for w in ["sign in", "login", "bot", "cookie", "forbidden", "permission"]):
			return False, "Cookies YouTube không hợp lệ hoặc đã hết hạn."
		return False, f"Không thể kết nối đến YouTube để xác thực cookies: {err}"


def classify_extraction_error(error_str: str) -> YouTubeError:
    """Map yt-dlp error string to a stable AppView domain exception."""
    lower = error_str.lower()

    if any(phrase in lower for phrase in [
        "sign in to confirm your age",
        "confirm your age",
        "age-restricted",
        "sign in to confirm you’re not a bot",
        "sign in to confirm you're not a bot",
        "requires authentication",
        "login required",
    ]):
        return SourceAuthRequiredError(
            "This YouTube video requires an authenticated account with permission to access it."
        )

    if any(phrase in lower for phrase in [
        "private video",
        "this video is private",
        "access denied",
        "permission to access",
    ]):
        return SourceAccessDeniedError("Video này là riêng tư hoặc bị từ chối truy cập.")

    if any(phrase in lower for phrase in [
        "video unavailable",
        "does not exist",
        "has been removed",
        "not found",
    ]):
        return SourceNotFoundError("Không tìm thấy video YouTube này (video có thể đã bị xóa hoặc không tồn tại).")

    if "playlist" in lower and "entries" in lower:
        return PlaylistNotSupportedError(
            "Danh sách phát (playlist) chưa được hỗ trợ. Vui lòng cung cấp liên kết video đơn lẻ."
        )

    return YouTubeError("Không thể phân tích video YouTube.")
